In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d


In [2]:
trials=100_00_00       #total simulated events
low=-1;high=1;interval=high-low
test=interval*np.random.rand(trials,3)+low
#test
x=test[:,0]
y=test[:,1]
z=test[:,2]

In [3]:
x

array([-0.48942824, -0.41773957, -0.55947065, ...,  0.7801382 ,
       -0.86404714,  0.90284525])

In [4]:
y

array([-0.20906625,  0.63456529, -0.58388209, ..., -0.2699826 ,
        0.73485268, -0.51470937])

In [5]:
z

array([ 0.30606779, -0.40872605,  0.12331796, ...,  0.24316702,
        0.16178463,  0.02578501])

In [6]:

r=np.sqrt(x**2+y**2+z**2)
r

array([0.61394315, 0.86269139, 0.81800552, ..., 0.86060236, 1.14575747,
       1.03957691])

In [7]:
test=np.column_stack((test,r))

In [8]:
df=pd.DataFrame(test,columns=['x','y','z','r']) #data frame with x,y,z and r
df.head()

x         y         z         r
0 -0.489428 -0.209066  0.306068  0.613943
1 -0.417740  0.634565 -0.408726  0.862691
2 -0.559471 -0.583882  0.123318  0.818006
3  0.400094 -0.732474 -0.269299  0.876992
4  0.284732  0.183006  0.365417  0.498089

In [9]:
df_less=df[df.r<0.5]          #data frame with r<0.5 (radius of the bead)
df_less.head()
total_counts=df_less.shape[0]
total_counts

65097

In [10]:
# %matplotlib inline
# fig = plt.figure()
# ax = fig.add_subplot(projection='3d')
# ax.scatter(df_less.x,df_less.y,df_less.z)

In [11]:
#this function give the normal distance from a point to the surface of the sphere

def get_upward_distance(x,y,z,dz=0.001,r=0.5):
    '''
    returns normal distance from a point in the sphere to the surface as well as the z co-ordinate in the sphere
    '''
    #z=np.abs(z)
    d=np.sqrt(x**2+y**2+z**2)
    if z==-0.5: return 1.0,0.5
    z_up=0
    #print(f"before while z_up: {z_up}")
    while(d<r):
        z+=dz
        #print(f"Inside while z: {z}")
        z_up+=dz
        d=np.sqrt(x**2+y**2+z**2)
    #print(f"after while z_up: {z_up}")
    return z_up,z
        
    

In [12]:
#distance travelled in the bead

df_less['z_new']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[1],axis=1)
df_less['d_bead']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[0],axis=1)
df_less.head()

<ipython-input-12-c38b61caed6c>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_less['z_new']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[1],axis=1)
<ipython-input-12-c38b61caed6c>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_less['d_bead']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[0],axis=1)


x         y         z         r     z_new  d_bead
4   0.284732  0.183006  0.365417  0.498089  0.368417   0.003
21 -0.196257  0.265896  0.131632  0.355731  0.375632   0.244
22  0.008959  0.005327  0.268802  0.269004  0.500802   0.232
23 -0.397324 -0.009541  0.196836  0.443511  0.303836   0.107
47 -0.209789  0.186374 -0.190780  0.339329  0.414220   0.605

In [13]:
#distance travelled in the button
button_thickness=3.0
df_less['d_button']=button_thickness/2.-df_less['z_new'] #Thickness of button is 3 mm and thickness above 0 is 1.5 mm
df_less.head()

<ipython-input-13-e6d322812297>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_less['d_button']=button_thickness/2.-df_less['z_new'] #Thickness of button is 3 mm and thickness above 0 is 1.5 mm


x         y         z         r     z_new  d_bead  d_button
4   0.284732  0.183006  0.365417  0.498089  0.368417   0.003  1.131583
21 -0.196257  0.265896  0.131632  0.355731  0.375632   0.244  1.124368
22  0.008959  0.005327  0.268802  0.269004  0.500802   0.232  0.999198
23 -0.397324 -0.009541  0.196836  0.443511  0.303836   0.107  1.196164
47 -0.209789  0.186374 -0.190780  0.339329  0.414220   0.605  1.085780

In [14]:
#changing mm to cm
mm_to_cm=0.1
df_less=df_less*mm_to_cm
df_less.head()

x         y         z         r     z_new  d_bead  d_button
4   0.028473  0.018301  0.036542  0.049809  0.036842  0.0003  0.113158
21 -0.019626  0.026590  0.013163  0.035573  0.037563  0.0244  0.112437
22  0.000896  0.000533  0.026880  0.026900  0.050080  0.0232  0.099920
23 -0.039732 -0.000954  0.019684  0.044351  0.030384  0.0107  0.119616
47 -0.020979  0.018637 -0.019078  0.033933  0.041422  0.0605  0.108578

$ P_{transmission} = e^{-\frac{x}{\lambda}} $ <br>

x is thickness and $\lambda$ is attenuation length
<br> $\lambda = \frac{1}{\rho \cdot \mu} $ <br>
$ P_{transmission} = e^{-\mu \cdot \rho \cdot x} $ <br>

$ \mu $ ($cm^2/g$) <br> $ \rho $ ($g/cm^3$) <br> $\lambda (cm)$ <br>
$ \mu$ from https://physics.nist.gov/PhysRefData/Xcom/html/xcom1.html
<br>
Tranmission factor from: https://www.ezag.com/home/products/isotope_products/isotrak_calibration_sources/reference_sources/gamma_sources/point_sources/#c601

# fMaterialsManager->AddMaterial("Acrylic","C5-H8-O2",1.18*g/cm3,"")
# ceramic: O7410-Na300-Ca60-Mg10-Al600-Si1600-Pb4


![image](beadcomposition.png)

In [15]:
#Probabality of scatering from the button
button_density = 1.18        #g/cm^3 (from simulation data)
button_mu_pb   = 3.262E-01   # C5H8O2 for 47keV (0.047 MeV) gamma rays
bead_mu_pb     = 3.195E-01   #47 keV pb-21O for ceramic=> O7410Na300Ca60Mg10Al600Si1600Pb4

#trnasmission factors from manufacturer
transmission_pb=0.964   #47 keV pb-210

transmission_am=0.958   #60 keV am-241



#button_mu_am=0.1815    #60 keV am-241
#lambda calculation for acrylic button  (C5H802)
#fMaterialsManager->AddMaterial("Acrylic","C5-H8-O2",1.18*g/cm3,"");
#density is from oldmc




def transmission_prob(x,mu,rho):
    '''reutrns button transmission probability'''
    #return (1-np.exp(-1.0*x*mu*rho))
    return (np.exp(-1.0*x*mu*rho))

    
    
    

In [16]:
#adding the transmississin though button
df_less['button_transmission_prob']=df_less.apply(lambda x:transmission_prob(x['d_button'],button_mu_pb,button_density),axis=1)
df_less.head()

x         y         z         r     z_new  d_bead  d_button  \
4   0.028473  0.018301  0.036542  0.049809  0.036842  0.0003  0.113158   
21 -0.019626  0.026590  0.013163  0.035573  0.037563  0.0244  0.112437   
22  0.000896  0.000533  0.026880  0.026900  0.050080  0.0232  0.099920   
23 -0.039732 -0.000954  0.019684  0.044351  0.030384  0.0107  0.119616   
47 -0.020979  0.018637 -0.019078  0.033933  0.041422  0.0605  0.108578   

    button_transmission_prob  
4                   0.957379  
21                  0.957644  
22                  0.962269  
23                  0.955002  
47                  0.959068

In [34]:
#creating the random number bewteen 0 and 1, if the prob_product is greater than random number add 1 else add 0
def random_assign(x):
    if x>np.random.rand():
        return 1
    return 0
    

In [38]:
#adding the transmississin though button
bead_density=3.6 #g/cm^3  
df_less['bead_transmission_prob']=df_less.apply(lambda x:transmission_prob(x['d_bead'],bead_mu_pb,bead_density),axis=1)
df_less.head()

x         y         z         r     z_new  d_bead  d_button  \
4   0.028473  0.018301  0.036542  0.049809  0.036842  0.0003  0.113158   
21 -0.019626  0.026590  0.013163  0.035573  0.037563  0.0244  0.112437   
22  0.000896  0.000533  0.026880  0.026900  0.050080  0.0232  0.099920   
23 -0.039732 -0.000954  0.019684  0.044351  0.030384  0.0107  0.119616   
47 -0.020979  0.018637 -0.019078  0.033933  0.041422  0.0605  0.108578   

    button_transmission_prob  bead_transmission_prob  prob_product  
4                   0.957379                0.999655      0.957369  
21                  0.957644                0.972325      0.956898  
22                  0.962269                0.973668      0.961556  
23                  0.955002                0.987768      0.954675  
47                  0.959068                0.932779      0.957216

In [39]:
N_generated=df_less.shape[0]
#df_less['N_emitted']=df_less['button_transmission_prob']*df_less['bead_transmission_prob']*N_generated
df_less['prob_product']=df_less['button_transmission_prob']*df_less['bead_transmission_prob']
df_less.head()

x         y         z         r     z_new  d_bead  d_button  \
4   0.028473  0.018301  0.036542  0.049809  0.036842  0.0003  0.113158   
21 -0.019626  0.026590  0.013163  0.035573  0.037563  0.0244  0.112437   
22  0.000896  0.000533  0.026880  0.026900  0.050080  0.0232  0.099920   
23 -0.039732 -0.000954  0.019684  0.044351  0.030384  0.0107  0.119616   
47 -0.020979  0.018637 -0.019078  0.033933  0.041422  0.0605  0.108578   

    button_transmission_prob  bead_transmission_prob  prob_product  
4                   0.957379                0.999655      0.957048  
21                  0.957644                0.972325      0.931142  
22                  0.962269                0.973668      0.936931  
23                  0.955002                0.987768      0.943320  
47                  0.959068                0.932779      0.894598

In [40]:
avg_of_prob=round(df_less['prob_product'].mean(),3)
avg_of_prob

0.917

In [41]:
avg_random=round(df_less['prob_product'].apply(lambda x:random_assign(x)).mean(),3)
avg_random

0.917

# IGNORE BELOW THIS

In [34]:
for i in np.arange(0,10):
    test=get_prob(i)
    print(f"test :{test}")
df_less.head()
    

test :[0, 0.958]
test :[1, 0.946]
test :[2, 0.935]
test :[3, 0.924]
test :[4, 0.913]
test :[5, 0.903]
test :[6, 0.892]
test :[7, 0.882]
test :[8, 0.872]
test :[9, 0.862]


x         y         z         r     z_new  d_bead  d_button  \
3   0.047497  0.006968 -0.003179  0.048111  0.014021  0.0172  0.135979   
12  0.023846 -0.033606  0.026520  0.049003  0.028320  0.0018  0.121680   
19  0.024133  0.033255 -0.008861  0.042034  0.028539  0.0374  0.121461   
21 -0.025329  0.021287 -0.002507  0.033181  0.037493  0.0400  0.112507   
27  0.002256 -0.046914 -0.006089  0.047361  0.017211  0.0233  0.132789   

    button_transmission_prob  bead_transmission_prob  prob_product  
3                   0.949006                0.951745      0.903211  
12                  0.954243                0.994837      0.949317  
19                  0.954324                0.898037      0.857018  
21                  0.957619                0.891348      0.853572  
27                  0.950172                0.935196      0.888597

In [22]:
def get_prob(bead_density):
    '''
    returns the net prob of transmission for the chosen density of bead
    '''
    df_less['bead_transmission_prob']=df_less.apply(lambda x:transmission_prob(x['d_bead'],bead_mu_pb,bead_density),axis=1)
    df_less['prob_product']=df_less['button_transmission_prob']*df_less['bead_transmission_prob']
    avg_prob=round(df_less['prob_product'].mean(),3)
    return [bead_density,avg_prob]

In [33]:
for i in np.linspace(0,1,0.1):
    test=get_prob(i)
    print(f"test :{test}")

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
get_prob(0.3)

[0.3, 0.954]

In [81]:
avg_prob=round(df_less['prob_product'].mean(),3)
avg_prob

0.954

In [87]:
prob=get_prob(0.1)

In [88]:
prob

[0.3, 0.956]

In [89]:
for i in range(0.1,10.0,0.1):
    prob=get_prob(i)
    print(f"prob: {prob}")

TypeError: 'float' object cannot be interpreted as an integer