In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d


In [2]:
trials=100_00_00       #total simulated events
low=-1;high=1;interval=high-low
test=interval*np.random.rand(trials,3)+low
#test
x=test[:,0]
y=test[:,1]
z=test[:,2]

In [3]:
x

array([ 0.58921989,  0.52727846,  0.51541434, ..., -0.90247302,
        0.77557143, -0.31750351])

In [4]:
y

array([-0.95711113, -0.47290578, -0.0783168 , ..., -0.65099603,
       -0.45457009,  0.50184163])

In [5]:
z

array([ 0.60966704,  0.41310271,  0.46077284, ..., -0.81154267,
        0.94976864,  0.54875563])

In [6]:

r=np.sqrt(x**2+y**2+z**2)
r

array([1.27864604, 0.81994896, 0.69577085, ..., 1.37726355, 1.30774825,
       0.80857049])

In [7]:
test=np.column_stack((test,r))

In [8]:
df=pd.DataFrame(test,columns=['x','y','z','r']) #data frame with x,y,z and r
df.head()

x         y         z         r
0  0.589220 -0.957111  0.609667  1.278646
1  0.527278 -0.472906  0.413103  0.819949
2  0.515414 -0.078317  0.460773  0.695771
3 -0.835659  0.803216  0.544306  1.280528
4  0.032929 -0.697891 -0.666253  0.965417

In [9]:
df_less=df[df.r<0.5]          #data frame with r<0.5 (radius of the bead)
df_less.head()
total_counts=df_less.shape[0]
total_counts

65379

In [10]:
# %matplotlib inline
# fig = plt.figure()
# ax = fig.add_subplot(projection='3d')
# ax.scatter(df_less.x,df_less.y,df_less.z)

In [11]:
#this function give the normal distance from a point to the surface of the sphere

def get_upward_distance(x,y,z,dz=0.001,r=0.5):
    '''
    returns normal distance from a point in the sphere to the surface as well as the z co-ordinate in the sphere
    '''
    #z=np.abs(z)
    d=np.sqrt(x**2+y**2+z**2)
    if z==-0.5: return 1.0,0.5
    z_up=0
    #print(f"before while z_up: {z_up}")
    while(d<r):
        z+=dz
        #print(f"Inside while z: {z}")
        z_up+=dz
        d=np.sqrt(x**2+y**2+z**2)
    #print(f"after while z_up: {z_up}")
    return z_up,z
        
    

In [12]:
#distance travelled in the bead

df_less['z_new']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[1],axis=1)
df_less['d_bead']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[0],axis=1)
df_less.head()

/tmp/ipykernel_4988/2709360843.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_less['z_new']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[1],axis=1)
/tmp/ipykernel_4988/2709360843.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_less['d_bead']=df_less.apply(lambda x:get_upward_distance(x['x'],x['y'],x['z'])[0],axis=1)


x         y         z         r     z_new  d_bead
10 -0.125665 -0.285462 -0.288042  0.424557  0.390958   0.679
40 -0.128329 -0.086420  0.278886  0.318926  0.475886   0.197
51  0.355255 -0.086812 -0.114015  0.383069  0.340985   0.455
53 -0.055755  0.311893  0.297357  0.434519  0.387357   0.090
89 -0.148706  0.049641 -0.408563  0.437609  0.475437   0.884

In [13]:
#distance travelled in the button
button_thickness=3.0
df_less['d_button']=button_thickness/2.-df_less['z_new'] #Thickness of button is 3 mm and thickness above 0 is 1.5 mm
df_less.head()

/tmp/ipykernel_4988/1364162647.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_less['d_button']=button_thickness/2.-df_less['z_new'] #Thickness of button is 3 mm and thickness above 0 is 1.5 mm


x         y         z         r     z_new  d_bead  d_button
10 -0.125665 -0.285462 -0.288042  0.424557  0.390958   0.679  1.109042
40 -0.128329 -0.086420  0.278886  0.318926  0.475886   0.197  1.024114
51  0.355255 -0.086812 -0.114015  0.383069  0.340985   0.455  1.159015
53 -0.055755  0.311893  0.297357  0.434519  0.387357   0.090  1.112643
89 -0.148706  0.049641 -0.408563  0.437609  0.475437   0.884  1.024563

In [14]:
#changing mm to cm
mm_to_cm=0.1
df_less=df_less*mm_to_cm
df_less.head()

x         y         z         r     z_new  d_bead  d_button
10 -0.012567 -0.028546 -0.028804  0.042456  0.039096  0.0679  0.110904
40 -0.012833 -0.008642  0.027889  0.031893  0.047589  0.0197  0.102411
51  0.035526 -0.008681 -0.011401  0.038307  0.034099  0.0455  0.115901
53 -0.005575  0.031189  0.029736  0.043452  0.038736  0.0090  0.111264
89 -0.014871  0.004964 -0.040856  0.043761  0.047544  0.0884  0.102456

$ P_{transmission} = e^{-\frac{x}{\lambda}} $ <br>

x is thickness and $\lambda$ is attenuation length
<br> $\lambda = \frac{1}{\rho \cdot \mu} $ <br>
$ P_{transmission} = e^{-\mu \cdot \rho \cdot x} $ <br>

$ \mu $ ($cm^2/g$) <br> $ \rho $ ($g/cm^3$) <br> $\lambda (cm)$ <br>
$ \mu$ from https://physics.nist.gov/PhysRefData/Xcom/html/xcom1.html
<br>
Tranmission factor from: https://www.ezag.com/home/products/isotope_products/isotrak_calibration_sources/reference_sources/gamma_sources/point_sources/#c601

# fMaterialsManager->AddMaterial("Acrylic","C5-H8-O2",1.18*g/cm3,"")
# ceramic: O7410-Na300-Ca60-Mg10-Al600-Si1600-Pb4


![image](beadcomposition.png)

In [19]:
#Probabality of scatering from the button

button_density = 1.10         #.18        #g/cm^3 (from simulation data)
#button_mu_pb   = 0.1976       #C5H8O2 for 47keV (0.047 MeV) gamma rays
bead_mu_pb     = 3.195E-01    #47 keV pb-21O for ceramic=> O7410Na300Ca60Mg10Al600Si1600Pb4
bead_mu_am     = 2.314E-01    #60 keV am-241 for ceramic=> O7410Na300Ca60Mg10Al600Si1600Pb4

button_mu_pb =    1.797E-01     #C870O98N32
button_mu_am =    1.669E-01     #60 keV Am-241



#trnasmission factors from manufacturer
transmission_pb=0.964   #47 keV pb-210

transmission_am=0.958   #60 keV am-241

#Am-241 0.958


#button_mu_am=0.1815    #60 keV am-241
#lambda calculation for acrylic button  (C5H802)
#fMaterialsManager->AddMaterial("Acrylic","C5-H8-O2",1.18*g/cm3,"");
#density is from oldmc




def transmission_prob(x,mu,rho):
    '''reutrns button transmission probability'''
    #return (1-np.exp(-1.0*x*mu*rho))
    return (np.exp(-1.0*x*mu*rho))

    
    
    

In [20]:
#adding the transmississin though button
df_less['button_transmission_prob_pb']=df_less.apply(lambda x:transmission_prob(x['d_button'],button_mu_pb,button_density),axis=1)
df_less['button_transmission_prob_am']=df_less.apply(lambda x:transmission_prob(x['d_button'],button_mu_am,button_density),axis=1)
df_less.head()

x         y         z         r     z_new  d_bead  d_button  \
10 -0.012567 -0.028546 -0.028804  0.042456  0.039096  0.0679  0.110904   
40 -0.012833 -0.008642  0.027889  0.031893  0.047589  0.0197  0.102411   
51  0.035526 -0.008681 -0.011401  0.038307  0.034099  0.0455  0.115901   
53 -0.005575  0.031189  0.029736  0.043452  0.038736  0.0090  0.111264   
89 -0.014871  0.004964 -0.040856  0.043761  0.047544  0.0884  0.102456   

    button_transmission_prob_pb  button_transmission_prob_am  \
10                     0.978316                     0.979845   
40                     0.979960                     0.981374   
51                     0.977350                     0.978946   
53                     0.978246                     0.979780   
89                     0.979951                     0.981366   

    bead_transmission_prob_pb  
10                   0.974303  
40                   0.992475  
51                   0.982707  
53                   0.996555  
89                   0.966675

In [21]:
#creating the random number bewteen 0 and 1, if the prob_product is greater than random number add 1 else add 0
def random_assign(x):
    if x>np.random.rand():
        return 1
    return 0
    

In [82]:
#adding the transmississin though button
bead_density=2.5#g/cm^3  
df_less['bead_transmission_prob_pb']=df_less.apply(lambda x:transmission_prob(x['d_bead'],bead_mu_pb,bead_density),axis=1)
df_less['bead_transmission_prob_am']=df_less.apply(lambda x:transmission_prob(x['d_bead'],bead_mu_am,bead_density),axis=1)
df_less.head()

x         y         z         r     z_new  d_bead  d_button  \
10 -0.012567 -0.028546 -0.028804  0.042456  0.039096  0.0679  0.110904   
40 -0.012833 -0.008642  0.027889  0.031893  0.047589  0.0197  0.102411   
51  0.035526 -0.008681 -0.011401  0.038307  0.034099  0.0455  0.115901   
53 -0.005575  0.031189  0.029736  0.043452  0.038736  0.0090  0.111264   
89 -0.014871  0.004964 -0.040856  0.043761  0.047544  0.0884  0.102456   

    button_transmission_prob_pb  button_transmission_prob_am  \
10                     0.978316                     0.979845   
40                     0.979960                     0.981374   
51                     0.977350                     0.978946   
53                     0.978246                     0.979780   
89                     0.979951                     0.981366   

    bead_transmission_prob_pb  bead_transmission_prob_am  prob_product_pb  \
10                   0.947209                   0.961481         0.928683   
40                   0.984388                   0.988668         0.965268   
51                   0.964309                   0.974022         0.943839   
53                   0.992837                   0.994807         0.971519   
89                   0.931826                   0.950146         0.915726   

    prob_product_am  
10         0.943584  
40         0.970696  
51         0.954519  
53         0.974895  
89         0.934350

In [83]:
N_generated=df_less.shape[0]
#df_less['N_emitted']=df_less['button_transmission_prob']*df_less['bead_transmission_prob']*N_generated
df_less['prob_product_pb']=df_less['button_transmission_prob_pb']*df_less['bead_transmission_prob_pb']
df_less['prob_product_am']=df_less['button_transmission_prob_am']*df_less['bead_transmission_prob_am']
df_less.head()

x         y         z         r     z_new  d_bead  d_button  \
10 -0.012567 -0.028546 -0.028804  0.042456  0.039096  0.0679  0.110904   
40 -0.012833 -0.008642  0.027889  0.031893  0.047589  0.0197  0.102411   
51  0.035526 -0.008681 -0.011401  0.038307  0.034099  0.0455  0.115901   
53 -0.005575  0.031189  0.029736  0.043452  0.038736  0.0090  0.111264   
89 -0.014871  0.004964 -0.040856  0.043761  0.047544  0.0884  0.102456   

    button_transmission_prob_pb  button_transmission_prob_am  \
10                     0.978316                     0.979845   
40                     0.979960                     0.981374   
51                     0.977350                     0.978946   
53                     0.978246                     0.979780   
89                     0.979951                     0.981366   

    bead_transmission_prob_pb  bead_transmission_prob_am  prob_product_pb  \
10                   0.947209                   0.961481         0.926670   
40                   0.984388                   0.988668         0.964661   
51                   0.964309                   0.974022         0.942468   
53                   0.992837                   0.994807         0.971239   
89                   0.931826                   0.950146         0.913144   

    prob_product_am  
10         0.942103  
40         0.970253  
51         0.953515  
53         0.974692  
89         0.932441

In [84]:
#avg_of_prob_pb=round(df_less['prob_product_pb'].mean(),3)
avg_of_prob_am=round(df_less['prob_product_am'].mean(),3)
avg_of_prob_am

0.959

In [85]:
avg_random=round(df_less['prob_product_am'].apply(lambda x:random_assign(x)).mean(),3)
avg_random

0.958

# IGNORE BELOW THIS

In [94]:
def get_prob(bead_density):
    '''
    returns the net prob of transmission for the chosen density of bead
    '''
    df_less['bead_transmission_prob_am']=df_less.apply(lambda x:transmission_prob(x['d_bead'],bead_mu_am,bead_density),axis=1)
    df_less['prob_product_am']=df_less['button_transmission_prob_am']*df_less['bead_transmission_prob_am']
    avg_prob_am=round(df_less['prob_product_am'].mean(),3)
    return [bead_density,avg_prob_am]

In [ ]:
density_prob=[]
for i in np.arange(0,4,0.05):
    test=get_prob(i)
    density_prob.append(test)
    print(f"test :{test}")
df_less.head()
    

test :[0.0, 0.98]
test :[0.05, 0.979]
test :[0.1, 0.979]
test :[0.15000000000000002, 0.978]
test :[0.2, 0.978]
test :[0.25, 0.977]
test :[0.30000000000000004, 0.977]
test :[0.35000000000000003, 0.977]
test :[0.4, 0.976]
test :[0.45, 0.976]
test :[0.5, 0.975]
test :[0.55, 0.975]
test :[0.6000000000000001, 0.974]
test :[0.65, 0.974]
test :[0.7000000000000001, 0.974]
test :[0.75, 0.973]
test :[0.8, 0.973]
test :[0.8500000000000001, 0.972]
test :[0.9, 0.972]
test :[0.9500000000000001, 0.972]
test :[1.0, 0.971]
test :[1.05, 0.971]
test :[1.1, 0.97]
test :[1.1500000000000001, 0.97]
test :[1.2000000000000002, 0.969]
test :[1.25, 0.969]
test :[1.3, 0.969]
test :[1.35, 0.968]


In [33]:
for i in np.linspace(0,1,0.1):
    test=get_prob(i)
    print(f"test :{test}")

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
get_prob(0.3)

[0.3, 0.954]

In [81]:
avg_prob=round(df_less['prob_product'].mean(),3)
avg_prob

0.954

In [87]:
prob=get_prob(0.1)

In [88]:
prob

[0.3, 0.956]

In [89]:
for i in range(0.1,10.0,0.1):
    prob=get_prob(i)
    print(f"prob: {prob}")

TypeError: 'float' object cannot be interpreted as an integer